# Web Scraping to SQL Assignment

### I first imported the libraries that I needed for the Assignment

In [1]:
import pandas as pd
import lxml.html
import requests
import sqlite3

#### I use the requests library to save the url to the r variable

In [2]:
r = requests.get("https://www.billboard.com/charts/year-end/2019/top-artists")

#### The html is used to detect the html syntax

In [3]:
html = lxml.html.fromstring(r.text)

#### I figured out the pathway to the ranking values and display it as a text

In [5]:
html.xpath('//div[@class="ye-chart-item__rank"]')[0].text

'\n1\n'

#### Here I gather all the value that is in the ranking column

In [6]:
for location_cell in html.xpath('//div[@class="ye-chart-item__rank"]'):
    print(location_cell, location_cell.xpath('string()'))

<Element div at 0x7fefd1dbfa40>
1

<Element div at 0x7fefd1dbf040>
2

<Element div at 0x7fefd1dbfae0>
3

<Element div at 0x7fefd1dbfb30>
4

<Element div at 0x7fefd1dbfb80>
5

<Element div at 0x7fefd1dbfbd0>
6

<Element div at 0x7fefd1dbfc20>
7

<Element div at 0x7fefd1dbfc70>
8

<Element div at 0x7fefd1dbfcc0>
9

<Element div at 0x7fefd1dbfd10>
10

<Element div at 0x7fefd1dbfd60>
11

<Element div at 0x7fefd1dbfdb0>
12

<Element div at 0x7fefd1dbfe00>
13

<Element div at 0x7fefd1dbfe50>
14

<Element div at 0x7fefd1dbfea0>
15

<Element div at 0x7fefd1dbfef0>
16

<Element div at 0x7fefd1dbff40>
17

<Element div at 0x7fefd1dbff90>
18

<Element div at 0x7fefd1e5a720>
19

<Element div at 0x7fefd1e5a180>
20

<Element div at 0x7fefd1e5a400>
21

<Element div at 0x7fefd1e5adb0>
22

<Element div at 0x7fefd1e5ad60>
23

<Element div at 0x7fefd1e5ad10>
24

<Element div at 0x7fefd1e5ac20>
25

<Element div at 0x7fefd1e5ac70>
26

<Element div at 0x7fefd1e5acc0>
27

<Element div at 0x7fefd1e5aea0>
28

<Element div at 0x7fefd1e5a8b0>
29

<Element div at 0x7fefd1e5a810>
30

<Element div at 0x7fefd1e5a630>
31

<Element div at 0x7fefd1e5a2c0>
32

<Element div at 0x7fefd1e5af40>
33

<Element div at 0x7fefd1e5af90>
34

<Element div at 0x7fefd1e5ab80>
35

<Element div at 0x7fefd1e5ae00>
36

<Element div at 0x7fefd1e5ae50>
37

<Element div at 0x7fefd1e94ef0>
38

<Element div at 0x7fefd1e94f90>
39

<Element div at 0x7fefd1e94cc0>
40

<Element div at 0x7fefd1e94d10>
41

<Element div at 0x7fefd1dc1040>
42

<Element div at 0x7fefd1dc1090>
43

<Element div at 0x7fefd1dc10e0>
44

<Element div at 0x7fefd1dc1130>
45

<Element div at 0x7fefd1dc1180>
46

<Element div at 0x7fefd1dc11d0>
47

<Element div at 0x7fefd1dc1220>
48

<Element div at 0x7fefd1dc1270>
49

<Element div at 0x7fefd1dc12c0>
50

<Element div at 0x7fefd1dc1310>
51

<Element div at 0x7fefd1dc1360>
52

<Element div at 0x7fefd1dc13b0>
53

<Element div at 0x7fefd1dc1400>
54

<Element div at 0x7fefd1dc1450>
55

<Element div at 0x7fefd1dc14a0>
56

<Element div at 0x7fefd1dc14f0>
57

<Element div at 0x7fefd1dc1540>
58

<Element div at 0x7fefd1dc1590>
59

<Element div at 0x7fefd1dc15e0>
60

<Element div at 0x7fefd1dc1630>
61

<Element div at 0x7fefd1dc1680>
62

<Element div at 0x7fefd1dc16d0>
63

<Element div at 0x7fefd1dc1720>
64

<Element div at 0x7fefd1dc1770>
65

<Element div at 0x7fefd1dc17c0>
66

<Element div at 0x7fefd1dc1810>
67

<Element div at 0x7fefd1dc1860>
68

<Element div at 0x7fefd1dc18b0>
69

<Element div at 0x7fefd1dc1900>
70

<Element div at 0x7fefd1dc1950>
71

<Element div at 0x7fefd1dc19a0>
72

<Element div at 0x7fefd1dc19f0>
73

<Element div at 0x7fefd1dc1a40>
74

<Element div at 0x7fefd1dc1a90>
75

<Element div at 0x7fefd1dc1ae0>
76

<Element div at 0x7fefd1dc1b30>
77

<Element div at 0x7fefd1dc1b80>
78

<Element div at 0x7fefd1dc1bd0>
79

<Element div at 0x7fefd1dc1c20>
80

<Element div at 0x7fefd1dc1c70>
81

<Element div at 0x7fefd1dc1cc0>
82

<Element div at 0x7fefd1dc1d10>
83

<Element div at 0x7fefd1dc1d60>
84

<Element div at 0x7fefd1dc1db0>
85

<Element div at 0x7fefd1dc1e00>
86

<Element div at 0x7fefd1dc1e50>
87

<Element div at 0x7fefd1dc1ea0>
88

<Element div at 0x7fefd1dc1ef0>
89

<Element div at 0x7fefd1dc1f40>
90

<Element div at 0x7fefd1dc1f90>
91

<Element div at 0x7fefd1dc2040>
92

<Element div at 0x7fefd1dc2090>
93

<Element div at 0x7fefd1dc20e0>
94

<Element div at 0x7fefd1dc2130>
95

<Element div at 0x7fefd1dc2180>
96

<Element div at 0x7fefd1dc21d0>
97

<Element div at 0x7fefd1dc2220>
98

<Element div at 0x7fefd1dc2270>
99

<Element div at 0x7fefd1dc22c0>
100

#### I found the artist value or name

In [7]:
html.xpath('//div[@class="ye-chart-item__title"]')[0].getchildren()[0].text

'\nPost Malone\n'

#### Here I gather all the value that is in the artist column

In [8]:
for location_cell in html.xpath('//div[@class="ye-chart-item__title"]'):
    print(location_cell, location_cell.xpath('string()'))

<Element div at 0x7fefd1dc2400>

Post Malone


<Element div at 0x7fefd1dc24a0>

Ariana Grande


<Element div at 0x7fefd1dc24f0>

Billie Eilish


<Element div at 0x7fefd1dc2540>

Khalid


<Element div at 0x7fefd1dc2590>

Drake


<Element div at 0x7fefd1dc25e0>

Travis Scott


<Element div at 0x7fefd1dc2630>

Ed Sheeran


<Element div at 0x7fefd1dc2680>

Taylor Swift


<Element div at 0x7fefd1dc26d0>

Lil Nas X


<Element div at 0x7fefd1dc2720>

Halsey


<Element div at 0x7fefd1dc2770>

Jonas Brothers


<Element div at 0x7fefd1dc27c0>

Juice WRLD


<Element div at 0x7fefd1dc2810>

Cardi B


<Element div at 0x7fefd1dc2860>

DaBaby


<Element div at 0x7fefd1dc28b0>

BTS


<Element div at 0x7fefd1dc2900>

Panic! At The Disco


<Element div at 0x7fefd1dc2950>

Luke Combs


<Element div at 0x7fefd1dc29a0>

Lil Baby


<Element div at 0x7fefd1dc29f0>

Shawn Mendes


<Element div at 0x7fefd1dc2a40>

Lizzo


<Element div at 0x7fefd1dc2a90>

Meek Mill


<Element div at 0x7fefd1dc2ae0>

Queen


<Element div at 0x7fefd1dc2b30>

Dan + Shay


<Element div at 0x7fefd1dc2b80>

A Boogie Wit da Hoodie


<Element div at 0x7fefd1dc2bd0>

P!nk


<Element div at 0x7fefd1dc2c20>

Chris Brown


<Element div at 0x7fefd1dc2c70>

XXXTENTACION


<Element div at 0x7fefd1dc2cc0>

J. Cole


<Element div at 0x7fefd1dc2d10>

Elton John


<Element div at 0x7fefd1dc2d60>

Imagine Dragons


<Element div at 0x7fefd1dc2db0>

Bad Bunny


<Element div at 0x7fefd1dc2e00>

Kodak Black


<Element div at 0x7fefd1dc2e50>

21 Savage


<Element div at 0x7fefd1dc2ea0>

YoungBoy Never Broke Again


<Element div at 0x7fefd1dc2ef0>

Gunna


<Element div at 0x7fefd1dc2f40>

Kane Brown


<Element div at 0x7fefd1dc2f90>

Lady Gaga


<Element div at 0x7fefd1dc2040>

Marshmello


<Element div at 0x7fefd1dc2090>

Thomas Rhett


<Element div at 0x7fefd1dc20e0>

Maroon 5


<Element div at 0x7fefd1dc2130>

Swae Lee


<Element div at 0x7fefd1dc2180>

Camila Cabello


<Element div at 0x7fefd1dc21d0>

Sam Smith


<Element div at 0x7fefd1dc2220>

YNW Melly


<Element div at 0x7fefd1dc2270>

The Rolling Stones


<Element div at 0x7fefd1dbf450>

5 Seconds Of Summer


<Element div at 0x7fefd1dbf400>

Lauren Daigle


<Element div at 0x7fefd1dbf360>

 Lil Tecca


<Element div at 0x7fefd1dbf2c0>

Metallica


<Element div at 0x7fefd1dbf950>

Bruno Mars


<Element div at 0x7fefd1dbf270>

Young Thug


<Element div at 0x7fefd1dbf7c0>

Ella Mai


<Element div at 0x7fefd1dbf810>

Bradley Cooper


<Element div at 0x7fefd1dbf310>

Lewis Capaldi


<Element div at 0x7fefd1dbf1d0>

Eminem


<Element div at 0x7fefd1dbf040>

Jason Aldean


<Element div at 0x7fefd1dbf3b0>

NF


<Element div at 0x7fefd1dbfa40>

Michael Buble


<Element div at 0x7fefd1dbf5e0>

Ava Max


<Element div at 0x7fefd1dbf900>

The Beatles


<Element div at 0x7fefd1dbf860>

Normani


<Element div at 0x7fefd1dbf630>

Florida Georgia Line


<Element div at 0x7fefd1dbf9f0>

twenty one pilots


<Element div at 0x7fefd1dbf540>

Billy Ray Cyrus


<Element div at 0x7fefd1dbfa90>

Chris Stapleton


<Element div at 0x7fefd1dbf4f0>

Summer Walker


<Element div at 0x7fefd1dbf4a0>

Morgan Wallen


<Element div at 0x7fefd1dbf130>

Bastille


<Element div at 0x7fefd1dbf090>

Offset


<Element div at 0x7fefd1dbfae0>

Trippie Redd


<Element div at 0x7fefd1dbfb30>

Tyler, The Creator


<Element div at 0x7fefd1dbfb80>

Future


<Element div at 0x7fefd1dbfbd0>

Lil Wayne


<Element div at 0x7fefd1dbfc20>

Blake Shelton


<Element div at 0x7fefd1dbfc70>

Justin Bieber


<Element div at 0x7fefd1dbfcc0>

City Girls


<Element div at 0x7fefd1dbfd10>

Blueface


<Element div at 0x7fefd1dbfd60>

Carrie Underwood


<Element div at 0x7fefd1dbfdb0>

Kanye West


<Element div at 0x7fefd1dbfe00>

DJ Khaled


<Element div at 0x7fefd1dbfe50>

Billy Joel


<Element div at 0x7fefd1dbfea0>

Eagles


<Element div at 0x7fefd1dbfef0>

Backstreet Boys


<Element div at 0x7fefd1dbff40>

Paul McCartney


<Element div at 0x7fefd1dbff90>

Megan Thee Stallion


<Element div at 0x7fefd1dbf770>

Maren Morris


<Element div at 0x7fefd1dbf6d0>

Bazzi


<Element div at 0x7fefd1dbf720>

Mustard


<Element div at 0x7fefd1dc6040>

6ix9ine


<Element div at 0x7fefd1dc6090>

Kendrick Lamar


<Element div at 0x7fefd1dc60e0>

Polo G


<Element div at 0x7fefd1dc6130>

Sheck Wes


<Element div at 0x7fefd1dc6180>

Migos


<Element div at 0x7fefd1dc61d0>

Lil Uzi Vert


<Element div at 0x7fefd1dc6220>

Nipsey Hussle


<Element div at 0x7fefd1dc6270>

Fleetwood Mac


<Element div at 0x7fefd1dc62c0>

The Weeknd


<Element div at 0x7fefd1dc6310>

Eric Church


<Element div at 0x7fefd1dc6360>

benny blanco


<Element div at 0x7fefd1dc63b0>

Luke Bryan

#### I noticed the new line character is present along with the value. I have to remove them before I continue on in my assignment.

In [9]:
[x.xpath("string()") for x in html.xpath('//div[@class="ye-chart-item__rank"]')]

['\n1\n',
 '\n2\n',
 '\n3\n',
 '\n4\n',
 '\n5\n',
 '\n6\n',
 '\n7\n',
 '\n8\n',
 '\n9\n',
 '\n10\n',
 '\n11\n',
 '\n12\n',
 '\n13\n',
 '\n14\n',
 '\n15\n',
 '\n16\n',
 '\n17\n',
 '\n18\n',
 '\n19\n',
 '\n20\n',
 '\n21\n',
 '\n22\n',
 '\n23\n',
 '\n24\n',
 '\n25\n',
 '\n26\n',
 '\n27\n',
 '\n28\n',
 '\n29\n',
 '\n30\n',
 '\n31\n',
 '\n32\n',
 '\n33\n',
 '\n34\n',
 '\n35\n',
 '\n36\n',
 '\n37\n',
 '\n38\n',
 '\n39\n',
 '\n40\n',
 '\n41\n',
 '\n42\n',
 '\n43\n',
 '\n44\n',
 '\n45\n',
 '\n46\n',
 '\n47\n',
 '\n48\n',
 '\n49\n',
 '\n50\n',
 '\n51\n',
 '\n52\n',
 '\n53\n',
 '\n54\n',
 '\n55\n',
 '\n56\n',
 '\n57\n',
 '\n58\n',
 '\n59\n',
 '\n60\n',
 '\n61\n',
 '\n62\n',
 '\n63\n',
 '\n64\n',
 '\n65\n',
 '\n66\n',
 '\n67\n',
 '\n68\n',
 '\n69\n',
 '\n70\n',
 '\n71\n',
 '\n72\n',
 '\n73\n',
 '\n74\n',
 '\n75\n',
 '\n76\n',
 '\n77\n',
 '\n78\n',
 '\n79\n',
 '\n80\n',
 '\n81\n',
 '\n82\n',
 '\n83\n',
 '\n84\n',
 '\n85\n',
 '\n86\n',
 '\n87\n',
 '\n88\n',
 '\n89\n',
 '\n90\n',
 '\n91\n',
 '\n92\n',
 '\n93\n',
 '\n94\n',
 '\n95\n',
 '\n96\n',
 '\n97\n',
 '\n98\n',
 '\n99\n',
 '\n100\n']

#### I used the map() and strip() to remove the new line characters in the value

In [10]:
rank = [x.xpath("string()") for x in html.xpath('//div[@class="ye-chart-item__rank"]')]
official_rank = map(str.strip, rank)

#### Again, the new line character is present along with the value. I have to remove them.

In [11]:
[x.xpath("string()") for x in html.xpath('//div[@class="ye-chart-item__title"]')]

['\n\nPost Malone\n\n',
 '\n\nAriana Grande\n\n',
 '\n\nBillie Eilish\n\n',
 '\n\nKhalid\n\n',
 '\n\nDrake\n\n',
 '\n\nTravis Scott\n\n',
 '\n\nEd Sheeran\n\n',
 '\n\nTaylor Swift\n\n',
 '\n\nLil Nas X\n\n',
 '\n\nHalsey\n\n',
 '\n\nJonas Brothers\n\n',
 '\n\nJuice WRLD\n\n',
 '\n\nCardi B\n\n',
 '\n\nDaBaby\n\n',
 '\n\nBTS\n\n',
 '\n\nPanic! At The Disco\n\n',
 '\n\nLuke Combs\n\n',
 '\n\nLil Baby\n\n',
 '\n\nShawn Mendes\n\n',
 '\n\nLizzo\n\n',
 '\n\nMeek Mill\n\n',
 '\n\nQueen\n\n',
 '\n\nDan + Shay\n\n',
 '\n\nA Boogie Wit da Hoodie\n\n',
 '\n\nP!nk\n\n',
 '\n\nChris Brown\n\n',
 '\n\nXXXTENTACION\n\n',
 '\n\nJ. Cole\n\n',
 '\n\nElton John\n\n',
 '\n\nImagine Dragons\n\n',
 '\n\nBad Bunny\n\n',
 '\n\nKodak Black\n\n',
 '\n\n21 Savage\n\n',
 '\n\nYoungBoy Never Broke Again\n\n',
 '\n\nGunna\n\n',
 '\n\nKane Brown\n\n',
 '\n\nLady Gaga\n\n',
 '\n\nMarshmello\n\n',
 '\n\nThomas Rhett\n\n',
 '\n\nMaroon 5\n\n',
 '\n\nSwae Lee\n\n',
 '\n\nCamila Cabello\n\n',
 '\n\nSam Smith\n\n',
 '\n\nYNW Melly\n\n',
 '\n\nThe Rolling Stones\n\n',
 '\n\n5 Seconds Of Summer\n\n',
 '\n\nLauren Daigle\n\n',
 '\n\n Lil Tecca\n\n',
 '\n\nMetallica\n\n',
 '\n\nBruno Mars\n\n',
 '\n\nYoung Thug\n\n',
 '\n\nElla Mai\n\n',
 '\n\nBradley Cooper\n\n',
 '\n\nLewis Capaldi\n\n',
 '\n\nEminem\n\n',
 '\n\nJason Aldean\n\n',
 '\n\nNF\n\n',
 '\n\nMichael Buble\n\n',
 '\n\nAva Max\n\n',
 '\n\nThe Beatles\n\n',
 '\n\nNormani\n\n',
 '\n\nFlorida Georgia Line\n\n',
 '\n\ntwenty one pilots\n\n',
 '\n\nBilly Ray Cyrus\n\n',
 '\n\nChris Stapleton\n\n',
 '\n\nSummer Walker\n\n',
 '\n\nMorgan Wallen\n\n',
 '\n\nBastille\n\n',
 '\n\nOffset\n\n',
 '\n\nTrippie Redd\n\n',
 '\n\nTyler, The Creator\n\n',
 '\n\nFuture\n\n',
 '\n\nLil Wayne\n\n',
 '\n\nBlake Shelton\n\n',
 '\n\nJustin Bieber\n\n',
 '\n\nCity Girls\n\n',
 '\n\nBlueface\n\n',
 '\n\nCarrie Underwood\n\n',
 '\n\nKanye West\n\n',
 '\n\nDJ Khaled\n\n',
 '\n\nBilly Joel\n\n',
 '\n\nEagles\n\n',
 '\n\nBackstreet Boys\n\n',
 '\n\nPaul McCartney\n\n',
 '\n\nMegan Thee Stallion\n\n',
 '\n\nMaren Morris\n\n',
 '\n\nBazzi\n\n',
 '\n\nMustard\n\n',
 '\n\n6ix9ine\n\n',
 '\n\nKendrick Lamar\n\n',
 '\n\nPolo G\n\n',
 '\n\nSheck Wes\n\n',
 '\n\nMigos\n\n',
 '\n\nLil Uzi Vert\n\n',
 '\n\nNipsey Hussle\n\n',
 '\n\nFleetwood Mac\n\n',
 '\n\nThe Weeknd\n\n',
 '\n\nEric Church\n\n',
 '\n\nbenny blanco\n\n',
 '\n \nLuke Bryan\n\n']

#### Like last time, I used map() and strip() to remove the new line character

In [12]:
name = [x.xpath("string()") for x in html.xpath('//div[@class="ye-chart-item__title"]')]
official_name = map(str.strip, name)

#### Once I clean up the data, I then put them in a data frame.

In [13]:
df = pd.DataFrame({
    "Rank"  :official_rank,
    "Artist":official_name
})
df

   Rank         Artist
0     1    Post Malone
1     2  Ariana Grande
2     3  Billie Eilish
3     4         Khalid
4     5          Drake
..  ...            ...
95   96  Fleetwood Mac
96   97     The Weeknd
97   98    Eric Church
98   99   benny blanco
99  100     Luke Bryan

[100 rows x 2 columns]

#### Verify that the data frame is correct

In [14]:
df

   Rank         Artist
0     1    Post Malone
1     2  Ariana Grande
2     3  Billie Eilish
3     4         Khalid
4     5          Drake
..  ...            ...
95   96  Fleetwood Mac
96   97     The Weeknd
97   98    Eric Church
98   99   benny blanco
99  100     Luke Bryan

[100 rows x 2 columns]

#### Use the info() function on the data frame.

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rank    100 non-null    object
 1   Artist  100 non-null    object
dtypes: object(2)
memory usage: 1.7+ KB

#### Use the describe() function to describe the Rank column

In [16]:
df.Rank.describe()

count     100
unique    100
top        35
freq        1
Name: Rank, dtype: object

#### Use the describe() function to describe the Artist column

In [17]:
df.Artist.describe()

count               100
unique              100
top       Lewis Capaldi
freq                  1
Name: Artist, dtype: object

#### Verify that the value is in the data frame

In [18]:
df.Artist.isin(['Post Malone'])

0      True
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: Artist, Length: 100, dtype: bool

#### Selecting the ranking and artist pair in the data frame and printing them out

In [19]:
for row in df[df.Artist.isin(["Post Malone"])].itertuples():
    print(row[1:])

('1', 'Post Malone')

#### Verifying that the ranking and artist output

In [20]:
row[1:]

('1', 'Post Malone')

#### I Connect to the SQLite database and insert the top 5 artist

In [21]:
db = sqlite3.connect(":memory:")
cursor = db.cursor()
cursor.execute("""
    CREATE TABLE LIST(RANK, ARTIST)
""")

for row in df[df.Artist.isin(["Post Malone"])].itertuples():
    insert_sql_syntax = """
        INSERT INTO LIST(
        RANK,
        ARTIST)
        VALUES (?,?)
    """
    cursor.execute(insert_sql_syntax, row[1:])
    
for row in df[df.Artist.isin(["Ariana Grande"])].itertuples():
    insert_sql_syntax = """
        INSERT INTO LIST(
        RANK,
        ARTIST)
        VALUES (?,?)
    """
    cursor.execute(insert_sql_syntax, row[1:])
    
for row in df[df.Artist.isin(["Billie Eilish"])].itertuples():
    insert_sql_syntax = """
        INSERT INTO LIST(
        RANK,
        ARTIST)
        VALUES (?,?)
    """
    cursor.execute(insert_sql_syntax, row[1:])
    
for row in df[df.Artist.isin(["Khalid"])].itertuples():
    insert_sql_syntax = """
        INSERT INTO LIST(
        RANK,
        ARTIST)
        VALUES (?,?)
    """
    cursor.execute(insert_sql_syntax, row[1:])
    
for row in df[df.Artist.isin(["Drake"])].itertuples():
    insert_sql_syntax = """
        INSERT INTO LIST(
        RANK,
        ARTIST)
        VALUES (?,?)
    """
    cursor.execute(insert_sql_syntax, row[1:])
db.commit()
#db.close()

### I tested my database by selecting specific values

In [22]:
for row in cursor.execute("""
    SELECT *
    FROM LIST
    WHERE ARTIST = "Post Malone" OR ARTIST = "Drake"
"""):
    print(row)

('1', 'Post Malone')
('5', 'Drake')

In [23]:
for row in cursor.execute("""
    SELECT *
    FROM LIST
    WHERE NOT ARTIST = "Post Malone"
"""):
    print(row)

('2', 'Ariana Grande')
('3', 'Billie Eilish')
('4', 'Khalid')
('5', 'Drake')